/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioWebDevelopmentRouteImport } from './routes/portfolio.web-development'
import { Route as PortfolioVideoProductionRouteImport } from './routes/portfolio.video-production'
import { Route as PortfolioPhotographyRouteImport } from './routes/portfolio.photography'
import { Route as PortfolioGraphicDesignRouteImport } from './routes/portfolio.graphic-design'
import { Route as PortfolioAdCampaignsRouteImport } from './routes/portfolio.ad-campaigns'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioWebDevelopmentRoute = PortfolioWebDevelopmentRouteImport.update({
  id: '/portfolio/web-development',
  path: '/portfolio/web-development',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioVideoProductionRoute =
  PortfolioVideoProductionRouteImport.update({
    id: '/portfolio/video-production',
    path: '/portfolio/video-production',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioPhotographyRoute = PortfolioPhotographyRouteImport.update({
  id: '/portfolio/photography',
  path: '/portfolio/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioGraphicDesignRoute = PortfolioGraphicDesignRouteImport.update({
  id: '/portfolio/graphic-design',
  path: '/portfolio/graphic-design',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioAdCampaignsRoute = PortfolioAdCampaignsRouteImport.update({
  id: '/portfolio/ad-campaigns',
  path: '/portfolio/ad-campaigns',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/portfolio/ad-campaigns': typeof PortfolioAdCampaignsRoute
  '/portfolio/graphic-design': typeof PortfolioGraphicDesignRoute
  '/portfolio/photography': typeof PortfolioPhotographyRoute
  '/portfolio/video-production': typeof PortfolioVideoProductionRoute
  '/portfolio/web-development': typeof PortfolioWebDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/portfolio/ad-campaigns': typeof PortfolioAdCampaignsRoute
  '/portfolio/graphic-design': typeof PortfolioGraphicDesignRoute
  '/portfolio/photography': typeof PortfolioPhotographyRoute
  '/portfolio/video-production': typeof PortfolioVideoProductionRoute
  '/portfolio/web-development': typeof PortfolioWebDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/portfolio/ad-campaigns': typeof PortfolioAdCampaignsRoute
  '/portfolio/graphic-design': typeof PortfolioGraphicDesignRoute
  '/portfolio/photography': typeof PortfolioPhotographyRoute
  '/portfolio/video-production': typeof PortfolioVideoProductionRoute
  '/portfolio/web-development': typeof PortfolioWebDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/portfolio/ad-campaigns'
    | '/portfolio/graphic-design'
    | '/portfolio/photography'
    | '/portfolio/video-production'
    | '/portfolio/web-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/portfolio/ad-campaigns'
    | '/portfolio/graphic-design'
    | '/portfolio/photography'
    | '/portfolio/video-production'
    | '/portfolio/web-development'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/portfolio/ad-campaigns'
    | '/portfolio/graphic-design'
    | '/portfolio/photography'
    | '/portfolio/video-production'
    | '/portfolio/web-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  PortfolioAdCampaignsRoute: typeof PortfolioAdCampaignsRoute
  PortfolioGraphicDesignRoute: typeof PortfolioGraphicDesignRoute
  PortfolioPhotographyRoute: typeof PortfolioPhotographyRoute
  PortfolioVideoProductionRoute: typeof PortfolioVideoProductionRoute
  PortfolioWebDevelopmentRoute: typeof PortfolioWebDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/web-development': {
      id: '/portfolio/web-development'
      path: '/portfolio/web-development'
      fullPath: '/portfolio/web-development'
      preLoaderRoute: typeof PortfolioWebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/video-production': {
      id: '/portfolio/video-production'
      path: '/portfolio/video-production'
      fullPath: '/portfolio/video-production'
      preLoaderRoute: typeof PortfolioVideoProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/photography': {
      id: '/portfolio/photography'
      path: '/portfolio/photography'
      fullPath: '/portfolio/photography'
      preLoaderRoute: typeof PortfolioPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/graphic-design': {
      id: '/portfolio/graphic-design'
      path: '/portfolio/graphic-design'
      fullPath: '/portfolio/graphic-design'
      preLoaderRoute: typeof PortfolioGraphicDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/ad-campaigns': {
      id: '/portfolio/ad-campaigns'
      path: '/portfolio/ad-campaigns'
      fullPath: '/portfolio/ad-campaigns'
      preLoaderRoute: typeof PortfolioAdCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  PortfolioAdCampaignsRoute: PortfolioAdCampaignsRoute,
  PortfolioGraphicDesignRoute: PortfolioGraphicDesignRoute,
  PortfolioPhotographyRoute: PortfolioPhotographyRoute,
  PortfolioVideoProductionRoute: PortfolioVideoProductionRoute,
  PortfolioWebDevelopmentRoute: PortfolioWebDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
